apiVersion: apps/v1
kind: StatefulSet 
metadata: 
       name: statefulset
       labels:
            app: statefulset
spec: 
    replicas: 3 
    template:
      metadata:  
         name: statefulset
         labels: 
            app: statefulset
      spec:
        containers:
            - name: mypodss-cont
              image: mysql:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: dbport
                  containerPort: 3306
                  protocol: TCP
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                          secretKeyRef:
                              name: secretkey1
                              key: DB_PASSWORD 
                - name: MYSQL_USER_NAME
                  valueFrom:
                          secretKeyRef:
                              name: secretkey1
                              key: DB_USER 
                          
    selector:
        matchLabels:
          app: statefulset